name: 'Setup Cosmopolitan-cmake-toolchain'
description: 'Setup Cosmopolitan with CMake support'
inputs:
  version:
    description: 'Cosmopolitan version'
    required: true
    default: '2.2'
outputs:
  cosmopolitan-root:
    description: "Root directory of Cosmopolitan"
    value: ${{ steps.set-outputs.outputs.cosmopolitan-root }}
  cmake-toolchain-file:
    description: "Cosmopolitan CMake toolchain file"
    value: ${{ steps.set-outputs.outputs.cmake-toolchain-file }}
runs:
  using: "composite"
  steps:
    - uses: actions/cache/restore@v3
      id: restore-cache
      with:
        path: ${{ github.action_path }}/../../cosmopolitan
        key: cosmopolitan-${{ matrix.platform.version}}
    - name: Download and extract cosmopolitan
      if: ${{ !steps.restore-cache.outputs.cache-hit }}
      shell: bash
      run: |
        filename=cosmopolitan-amalgamation-rel-${{ inputs.version }}.zip
        wget "https://github.com/jart/cosmopolitan/releases/download/${{ inputs.version }}/$filename" -O /tmp/$filename
        sudo unzip /tmp/$filename -d ${{ github.action_path }}/../../cosmopolitan
    - uses: actions/cache/save@v3
      if: ${{ !steps.restore-cache.outputs.cache-hit }}
      with:
        path: ${{ github.action_path }}/../../cosmopolitan
        key: cosmopolitan-${{ matrix.platform.version}}
    - name: Set output
      id: set-outputs
      shell: bash
      run: |
        echo "COSMOPOLITAN_ROOT=${{ github.action_path }}/../../cosmopolitan" >>$GITHUB_ENV
        echo "cosmopolitan-root=${{ github.action_path }}/../../cosmopolitan" >>$GITHUB_OUTPUT
        echo "cmake-toolchain-file=${{ github.action_path }}/../../cmake/cosmopolitan.cmake" >>$GITHUB_OUTPUT
