name: Workflow

on:
  push:
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        platform:
          - { name: Linux,    os: ubuntu-latest, version: '2.2' }

    runs-on: ${{ matrix.platform.os }}
    name: CI Cosmopolitan ${{ matrix.platform.version }} (${{ matrix.platform.name }})
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.11.1

      - uses: actions/cache/restore@v3
        id: restore-cache
        with:
          path: ~/cosmopolitan
          key: cosmopolitan-${{ matrix.platform.version}}
      - name: Download and extract cosmopolitan
        if: ${{ !steps.restore-cache.outputs.cache-hit }}
        run: |
          filename=cosmopolitan-amalgamation-rel-${{ matrix.platform.version }}.zip
          wget "https://github.com/jart/cosmopolitan/releases/download/2.2/$filename" -O /tmp/$filename
          sudo unzip /tmp/$filename -d ~/cosmopolitan
      - uses: actions/cache/save@v3
        with:
          path: ~/cosmopolitan
          key: cosmopolitan-${{ matrix.platform.version}}

      - name: Setup Cosmopolitan CMake environment
        run:
          echo "COSMOPOLITAN_ROOT=$HOME/cosmopolitan" >>$GITHUB_ENV
      - name: Configure (CMake)
        run: |
          cmake -S test -B test_build -GNinja \
            -DCMAKE_TOOLCHAIN_FILE=$PWD/cmake/cosmopolitan.cmake
      - name: Build (CMake)
        run: |
          cmake --build test_build --verbose
