name: Workflow

on:
  push:
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        platform:
          - { name: Linux,    os: ubuntu-latest, commit: 'master' }

    runs-on: ${{ matrix.platform.os }}
    name: CI Cosmopolitan ${{ matrix.platform.commit }} (${{ matrix.platform.name }})
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.11.1

      - uses: ./.github/setup
        name: 'Setup Cosmopolitan with CMake support'
        id: setup-cosmopolitan
        with:
          commit: ${{ matrix.platform.commit }}

      - name: Configure (CMake)
        run: |
          cmake -S test -B test_build -GNinja \
            -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-cosmopolitan.outputs.cmake-toolchain-file }}
      - name: Build (CMake)
        run: |
          cmake --build test_build --verbose
      - name: Test existence of .com files
        run: |
          rc=0
          test_existence() {
            if [ ! -f $1 ]; then
              echo "$1 DOES not exist!" >/dev/stderr;
              rc=1
            fi
          }
          test_existence test_build/hello_world.com
          exit $rc
